version: 0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: Psow7sbo6WQ8HuBCgT7YsIDe+WwpCy8jNM1NhZeWfni2jYoDbbhAuDTiy+nT1D3J
build_script:
- cmd:
    dotnet build src\Jail\Jail.csproj -c Release
    
    dotnet build src\Jail.Design\Jail.Design.csproj -c Release
    
    dotnet build src\Jail.HelpersForTests\Jail.HelpersForTests.csproj -c Release
test_script:
- ps: >-
    dotnet tool install -g coverlet.console

    dotnet tool install -g coveralls.net --version 1.0.0

    dotnet build src\Jail.sln -c Debug

    coverlet src\Jail.Tests\bin\Debug\netcoreapp2.2\Jail.Tests.dll --target "dotnet" --targetargs "test src\Jail.sln -c Debug --no-build" --format=opencover

    csmacnz.Coveralls --opencover -i coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
artifacts:
- path: '**\Release\**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: wDyA0UQeDdf4kkICVS9ZxsfaqPApmv+4z5QGPOdrhr53mZccvoDuIb02i/MjB1tJ
  skip_symbols: false
  artifact: NuGet
  on:
    branch: master